# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5702b9ba180c9bc6d814cebd3c4ea310e846563cbb3fa47a0ab7d11bc3ecfb81b2cf639b584aa13826d897fb853a8f46b70f531d5ef1f52fdd97e4e25e967966

test:
  secret_key_base: f1c84ae526fd75d877dedfe3df7192f8589ab8e7783a73ee87e8dddd451fd6c91b6152463eb5c56b888bfd635aba390ed1c7eaf3c769ebb593e41a7c1e51a415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
